# Generated by Django 3.2.9 on 2021-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='recovery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
