# Generated by Django 3.2.9 on 2021-11-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211116_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='death',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='recovery',
            new_name='recovered',
        ),
    ]
